inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/test_data/*'
    - 'gon.gemspec'

Lint/SuppressedException:
  AllowComments: true

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Naming/AccessorMethodName:
  Exclude:
    - 'lib/gon/jbuilder/parser.rb'
